# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppRunnerGroupSettings do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :container_image_tag,
    :container_image_url,
    :created_at,
    :created_by,
    :created_by_id,
    :env,
    :heart_beat_timeout,
    :id,
    :org_id,
    :otel_collector_config,
    :runner_api_url,
    :runner_group_id,
    :settings_refresh_timeout,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :container_image_tag => String.t | nil,
    :container_image_url => String.t | nil,
    :created_at => String.t | nil,
    :created_by => Nuon.Model.AppAccount.t | nil,
    :created_by_id => String.t | nil,
    :env => String.t | nil,
    :heart_beat_timeout => integer() | nil,
    :id => String.t | nil,
    :org_id => String.t | nil,
    :otel_collector_config => String.t | nil,
    :runner_api_url => String.t | nil,
    :runner_group_id => String.t | nil,
    :settings_refresh_timeout => integer() | nil,
    :updated_at => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_by, :struct, Nuon.Model.AppAccount)
  end
end

