# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppInstaller do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :apps,
    :created_at,
    :created_by,
    :created_by_id,
    :id,
    :metadata,
    :org_id,
    :type,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :apps => [Nuon.Model.AppApp.t] | nil,
    :created_at => String.t | nil,
    :created_by => Nuon.Model.AppAccount.t | nil,
    :created_by_id => String.t | nil,
    :id => String.t | nil,
    :metadata => Nuon.Model.AppInstallerMetadata.t | nil,
    :org_id => String.t | nil,
    :type => Nuon.Model.AppInstallerType.t | nil,
    :updated_at => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:apps, :list, Nuon.Model.AppApp)
     |> Deserializer.deserialize(:created_by, :struct, Nuon.Model.AppAccount)
     |> Deserializer.deserialize(:metadata, :struct, Nuon.Model.AppInstallerMetadata)
     |> Deserializer.deserialize(:type, :struct, Nuon.Model.AppInstallerType)
  end
end

