# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppRunner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :created_at,
    :created_by,
    :created_by_id,
    :display_name,
    :id,
    :jobs,
    :name,
    :org,
    :org_id,
    :runner_id,
    :runner_job,
    :status,
    :status_description,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :created_at => String.t | nil,
    :created_by => Nuon.Model.AppAccount.t | nil,
    :created_by_id => String.t | nil,
    :display_name => String.t | nil,
    :id => String.t | nil,
    :jobs => [Nuon.Model.AppRunnerJob.t] | nil,
    :name => String.t | nil,
    :org => Nuon.Model.AppOrg.t | nil,
    :org_id => String.t | nil,
    :runner_id => String.t | nil,
    :runner_job => Nuon.Model.AppRunnerJob.t | nil,
    :status => String.t | nil,
    :status_description => String.t | nil,
    :updated_at => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_by, :struct, Nuon.Model.AppAccount)
     |> Deserializer.deserialize(:jobs, :list, Nuon.Model.AppRunnerJob)
     |> Deserializer.deserialize(:org, :struct, Nuon.Model.AppOrg)
     |> Deserializer.deserialize(:runner_job, :struct, Nuon.Model.AppRunnerJob)
  end
end

