# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppCloudPlatformRegion do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :display_name,
    :icon,
    :name,
    :value
  ]

  @type t :: %__MODULE__{
    :display_name => String.t | nil,
    :icon => String.t | nil,
    :name => String.t | nil,
    :value => String.t | nil
  }

  def decode(value) do
    value
  end
end

