# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppSandboxRelease do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :created_at,
    :created_by,
    :created_by_id,
    :deprovision_policy_url,
    :id,
    :one_click_role_template_url,
    :provision_policy_url,
    :trust_policy_url,
    :updated_at,
    :version
  ]

  @type t :: %__MODULE__{
    :created_at => String.t | nil,
    :created_by => Nuon.Model.AppUserToken.t | nil,
    :created_by_id => String.t | nil,
    :deprovision_policy_url => String.t | nil,
    :id => String.t | nil,
    :one_click_role_template_url => String.t | nil,
    :provision_policy_url => String.t | nil,
    :trust_policy_url => String.t | nil,
    :updated_at => String.t | nil,
    :version => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_by, :struct, Nuon.Model.AppUserToken)
  end
end

