# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppRunnerJobExecution do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :created_at,
    :created_by,
    :created_by_id,
    :id,
    :org,
    :org_id,
    :result,
    :runner_job_id,
    :status,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :created_at => String.t | nil,
    :created_by => Nuon.Model.AppAccount.t | nil,
    :created_by_id => String.t | nil,
    :id => String.t | nil,
    :org => Nuon.Model.AppOrg.t | nil,
    :org_id => String.t | nil,
    :result => Nuon.Model.AppRunnerJobExecutionResult.t | nil,
    :runner_job_id => String.t | nil,
    :status => Nuon.Model.AppRunnerJobExecutionStatus.t | nil,
    :updated_at => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_by, :struct, Nuon.Model.AppAccount)
     |> Deserializer.deserialize(:org, :struct, Nuon.Model.AppOrg)
     |> Deserializer.deserialize(:result, :struct, Nuon.Model.AppRunnerJobExecutionResult)
     |> Deserializer.deserialize(:status, :struct, Nuon.Model.AppRunnerJobExecutionStatus)
  end
end

