# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppRole do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :createdBy,
    :created_at,
    :created_by_id,
    :id,
    :policies,
    :role_type,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :createdBy => Nuon.Model.AppAccount.t | nil,
    :created_at => String.t | nil,
    :created_by_id => String.t | nil,
    :id => String.t | nil,
    :policies => [Nuon.Model.AppPolicy.t] | nil,
    :role_type => Nuon.Model.AppRoleType.t | nil,
    :updated_at => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:createdBy, :struct, Nuon.Model.AppAccount)
     |> Deserializer.deserialize(:policies, :list, Nuon.Model.AppPolicy)
     |> Deserializer.deserialize(:role_type, :struct, Nuon.Model.AppRoleType)
  end
end

