# NOTE: This file is auto generated by OpenAPI Generator 7.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppAppInput do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :app_input_id,
    :created_at,
    :created_by,
    :created_by_id,
    :default,
    :description,
    :display_name,
    :id,
    :name,
    :org_id,
    :required,
    :sensitive,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :app_input_id => String.t | nil,
    :created_at => String.t | nil,
    :created_by => Nuon.Model.AppUserToken.t | nil,
    :created_by_id => String.t | nil,
    :default => String.t | nil,
    :description => String.t | nil,
    :display_name => String.t | nil,
    :id => String.t | nil,
    :name => String.t | nil,
    :org_id => String.t | nil,
    :required => boolean() | nil,
    :sensitive => boolean() | nil,
    :updated_at => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_by, :struct, Nuon.Model.AppUserToken)
  end
end

