# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppTerraformModuleComponentConfig do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :component_config_connection_id,
    :connected_github_vcs_config,
    :created_at,
    :created_by_id,
    :env_vars,
    :id,
    :public_git_vcs_config,
    :updated_at,
    :variables,
    :version
  ]

  @type t :: %__MODULE__{
    :component_config_connection_id => String.t | nil,
    :connected_github_vcs_config => Nuon.Model.AppConnectedGithubVcsConfig.t | nil,
    :created_at => String.t | nil,
    :created_by_id => String.t | nil,
    :env_vars => %{optional(String.t) => String.t} | nil,
    :id => String.t | nil,
    :public_git_vcs_config => Nuon.Model.AppPublicGitVcsConfig.t | nil,
    :updated_at => String.t | nil,
    :variables => %{optional(String.t) => String.t} | nil,
    :version => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:connected_github_vcs_config, :struct, Nuon.Model.AppConnectedGithubVcsConfig)
     |> Deserializer.deserialize(:public_git_vcs_config, :struct, Nuon.Model.AppPublicGitVcsConfig)
  end
end

