# NOTE: This file is auto generated by OpenAPI Generator 7.4.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppComponentReleaseStep do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :component_release_id,
    :created_at,
    :created_by,
    :created_by_id,
    :delay,
    :id,
    :install_deploys,
    :requested_install_ids,
    :status,
    :status_description,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :component_release_id => String.t | nil,
    :created_at => String.t | nil,
    :created_by => Nuon.Model.AppUserToken.t | nil,
    :created_by_id => String.t | nil,
    :delay => String.t | nil,
    :id => String.t | nil,
    :install_deploys => [Nuon.Model.AppInstallDeploy.t] | nil,
    :requested_install_ids => [String.t] | nil,
    :status => String.t | nil,
    :status_description => String.t | nil,
    :updated_at => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_by, :struct, Nuon.Model.AppUserToken)
     |> Deserializer.deserialize(:install_deploys, :list, Nuon.Model.AppInstallDeploy)
  end
end

