# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.AppRunnerGroup do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :created_at,
    :created_by,
    :created_by_id,
    :id,
    :org_id,
    :owner_id,
    :owner_type,
    :platform,
    :runners,
    :settings,
    :type,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :created_at => String.t | nil,
    :created_by => Nuon.Model.AppAccount.t | nil,
    :created_by_id => String.t | nil,
    :id => String.t | nil,
    :org_id => String.t | nil,
    :owner_id => String.t | nil,
    :owner_type => String.t | nil,
    :platform => Nuon.Model.AppAppRunnerType.t | nil,
    :runners => [Nuon.Model.AppRunner.t] | nil,
    :settings => Nuon.Model.AppRunnerGroupSettings.t | nil,
    :type => Nuon.Model.AppRunnerGroupType.t | nil,
    :updated_at => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_by, :struct, Nuon.Model.AppAccount)
     |> Deserializer.deserialize(:platform, :struct, Nuon.Model.AppAppRunnerType)
     |> Deserializer.deserialize(:runners, :list, Nuon.Model.AppRunner)
     |> Deserializer.deserialize(:settings, :struct, Nuon.Model.AppRunnerGroupSettings)
     |> Deserializer.deserialize(:type, :struct, Nuon.Model.AppRunnerGroupType)
  end
end

