# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.Planv1Plan do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :actual
  ]

  @type t :: %__MODULE__{
    :actual => any() | nil
  }

  def decode(value) do
    value
  end
end

