# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceCreateAppConfigRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :content,
    :generated_terraform_json
  ]

  @type t :: %__MODULE__{
    :content => String.t,
    :generated_terraform_json => String.t | nil
  }

  def decode(value) do
    value
  end
end

