# NOTE: This file is auto generated by OpenAPI Generator 7.6.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceCreateAppRunnerConfigRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :env_vars,
    :type
  ]

  @type t :: %__MODULE__{
    :env_vars => %{optional(String.t) => String.t} | nil,
    :type => Nuon.Model.AppAppRunnerType.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:type, :struct, Nuon.Model.AppAppRunnerType)
  end
end

