# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceCreateOrgUserRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :user_id
  ]

  @type t :: %__MODULE__{
    :user_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

