# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceAwsEcrImageConfigRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :aws_region,
    :iam_role_arn
  ]

  @type t :: %__MODULE__{
    :aws_region => String.t | nil,
    :iam_role_arn => String.t | nil
  }

  def decode(value) do
    value
  end
end

