# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceUpdateComponentRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :dependencies,
    :name,
    :var_name
  ]

  @type t :: %__MODULE__{
    :dependencies => [String.t] | nil,
    :name => String.t,
    :var_name => String.t | nil
  }

  def decode(value) do
    value
  end
end

