# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceAppConfigTemplate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :content,
    :filename,
    :format,
    :type
  ]

  @type t :: %__MODULE__{
    :content => String.t | nil,
    :filename => String.t | nil,
    :format => Nuon.Model.AppAppConfigFmt.t | nil,
    :type => Nuon.Model.ServiceAppConfigTemplateType.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:format, :struct, Nuon.Model.AppAppConfigFmt)
     |> Deserializer.deserialize(:type, :struct, Nuon.Model.ServiceAppConfigTemplateType)
  end
end

