# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceAppInstaller do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :app,
    :metadata,
    :sandbox_mode
  ]

  @type t :: %__MODULE__{
    :app => Nuon.Model.AppApp.t | nil,
    :metadata => Nuon.Model.AppAppInstallerMetadata.t | nil,
    :sandbox_mode => boolean() | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:app, :struct, Nuon.Model.AppApp)
     |> Deserializer.deserialize(:metadata, :struct, Nuon.Model.AppAppInstallerMetadata)
  end
end

