# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceCreateJobComponentConfigRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :args,
    :cmd,
    :env_vars,
    :image_url,
    :tag
  ]

  @type t :: %__MODULE__{
    :args => [String.t] | nil,
    :cmd => [String.t] | nil,
    :env_vars => %{optional(String.t) => String.t} | nil,
    :image_url => String.t,
    :tag => String.t
  }

  def decode(value) do
    value
  end
end

