# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceRenderedInstaller do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :apps,
    :metadata,
    :sandbox_mode
  ]

  @type t :: %__MODULE__{
    :apps => [Nuon.Model.AppApp.t] | nil,
    :metadata => Nuon.Model.AppInstallerMetadata.t | nil,
    :sandbox_mode => boolean() | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:apps, :list, Nuon.Model.AppApp)
     |> Deserializer.deserialize(:metadata, :struct, Nuon.Model.AppInstallerMetadata)
  end
end

