# NOTE: This file is auto generated by OpenAPI Generator 7.4.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceUpdateInstallerRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :links,
    :name,
    :post_install_markdown
  ]

  @type t :: %__MODULE__{
    :description => String.t,
    :links => Nuon.Model.ServiceUpdateInstallerRequestLinks.t | nil,
    :name => String.t,
    :post_install_markdown => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:links, :struct, Nuon.Model.ServiceUpdateInstallerRequestLinks)
  end
end

