# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceCreateComponentReleaseRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :auto_build,
    :build_id,
    :strategy
  ]

  @type t :: %__MODULE__{
    :auto_build => boolean() | nil,
    :build_id => String.t | nil,
    :strategy => Nuon.Model.ServiceCreateComponentReleaseRequestStrategy.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:strategy, :struct, Nuon.Model.ServiceCreateComponentReleaseRequestStrategy)
  end
end

