# NOTE: This file is auto generated by OpenAPI Generator 7.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceCreateInstallRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :aws_account,
    :azure_account,
    :inputs,
    :name
  ]

  @type t :: %__MODULE__{
    :aws_account => Nuon.Model.ServiceCreateInstallRequestAwsAccount.t | nil,
    :azure_account => Nuon.Model.ServiceCreateInstallRequestAzureAccount.t | nil,
    :inputs => %{optional(String.t) => String.t} | nil,
    :name => String.t
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:aws_account, :struct, Nuon.Model.ServiceCreateInstallRequestAwsAccount)
     |> Deserializer.deserialize(:azure_account, :struct, Nuon.Model.ServiceCreateInstallRequestAzureAccount)
  end
end

