# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceSetAppConfigStatusRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :status_description
  ]

  @type t :: %__MODULE__{
    :status => Nuon.Model.AppAppConfigStatus.t | nil,
    :status_description => String.t | nil
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, Nuon.Model.AppAppConfigStatus)
  end
end

