# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceCreateAppInputConfigRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :groups,
    :inputs
  ]

  @type t :: %__MODULE__{
    :groups => %{optional(String.t) => Nuon.Model.ServiceAppGroupRequest.t},
    :inputs => %{optional(String.t) => Nuon.Model.ServiceAppInputRequest.t}
  }

  alias Nuon.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:groups, :map, Nuon.Model.ServiceAppGroupRequest)
     |> Deserializer.deserialize(:inputs, :map, Nuon.Model.ServiceAppInputRequest)
  end
end

