# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nuon.Model.ServiceCreateInstallInputsRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :inputs
  ]

  @type t :: %__MODULE__{
    :inputs => %{optional(String.t) => String.t}
  }

  def decode(value) do
    value
  end
end

