# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.AppInstallInputs do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :created_at,
    :created_by_id,
    :id,
    :install_id,
    :org_id,
    :updated_at,
    :values
  ]

  @type t :: %__MODULE__{
    :created_at => String.t | nil,
    :created_by_id => String.t | nil,
    :id => String.t | nil,
    :install_id => String.t | nil,
    :org_id => String.t | nil,
    :updated_at => String.t | nil,
    :values => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

