# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.AppComponentBuild do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :component_config_connection_id,
    :created_at,
    :created_by_id,
    :git_ref,
    :id,
    :install_deploys,
    :releases,
    :status,
    :status_description,
    :updated_at,
    :vcs_connection_commit
  ]

  @type t :: %__MODULE__{
    :component_config_connection_id => String.t | nil,
    :created_at => String.t | nil,
    :created_by_id => String.t | nil,
    :git_ref => String.t | nil,
    :id => String.t | nil,
    :install_deploys => [NuonAPI.Model.AppInstallDeploy.t] | nil,
    :releases => [NuonAPI.Model.AppComponentRelease.t] | nil,
    :status => String.t | nil,
    :status_description => String.t | nil,
    :updated_at => String.t | nil,
    :vcs_connection_commit => NuonAPI.Model.AppVcsConnectionCommit.t | nil
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:install_deploys, :list, NuonAPI.Model.AppInstallDeploy)
     |> Deserializer.deserialize(:releases, :list, NuonAPI.Model.AppComponentRelease)
     |> Deserializer.deserialize(:vcs_connection_commit, :struct, NuonAPI.Model.AppVcsConnectionCommit)
  end
end

