# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.AppSandbox do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :created_at,
    :created_by_id,
    :description,
    :id,
    :name,
    :releases,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :created_at => String.t | nil,
    :created_by_id => String.t | nil,
    :description => String.t | nil,
    :id => String.t | nil,
    :name => String.t | nil,
    :releases => [NuonAPI.Model.AppSandboxRelease.t] | nil,
    :updated_at => String.t | nil
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:releases, :list, NuonAPI.Model.AppSandboxRelease)
  end
end

