# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.AppUserToken do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :created_at,
    :created_by_id,
    :email,
    :expires_at,
    :id,
    :issued_at,
    :issuer,
    :subject,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :created_at => String.t | nil,
    :created_by_id => String.t | nil,
    :email => String.t | nil,
    :expires_at => String.t | nil,
    :id => String.t | nil,
    :issued_at => String.t | nil,
    :issuer => String.t | nil,
    :subject => String.t | nil,
    :updated_at => String.t | nil
  }

  def decode(value) do
    value
  end
end

