# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.AppOrg do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :created_at,
    :created_by_id,
    :custom_cert,
    :id,
    :name,
    :sandbox_mode,
    :status,
    :status_description,
    :updated_at,
    :users,
    :vcs_connections
  ]

  @type t :: %__MODULE__{
    :created_at => String.t | nil,
    :created_by_id => String.t | nil,
    :custom_cert => boolean() | nil,
    :id => String.t | nil,
    :name => String.t | nil,
    :sandbox_mode => boolean() | nil,
    :status => String.t | nil,
    :status_description => String.t | nil,
    :updated_at => String.t | nil,
    :users => [NuonAPI.Model.AppUserOrg.t] | nil,
    :vcs_connections => [NuonAPI.Model.AppVcsConnection.t] | nil
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:users, :list, NuonAPI.Model.AppUserOrg)
     |> Deserializer.deserialize(:vcs_connections, :list, NuonAPI.Model.AppVcsConnection)
  end
end

