# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.AppInstallDeploy do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :build_id,
    :component_id,
    :component_name,
    :created_at,
    :created_by_id,
    :id,
    :install_component_id,
    :install_id,
    :release_id,
    :status,
    :status_description,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :build_id => String.t | nil,
    :component_id => String.t | nil,
    :component_name => String.t | nil,
    :created_at => String.t | nil,
    :created_by_id => String.t | nil,
    :id => String.t | nil,
    :install_component_id => String.t | nil,
    :install_id => String.t | nil,
    :release_id => String.t | nil,
    :status => String.t | nil,
    :status_description => String.t | nil,
    :updated_at => String.t | nil
  }

  def decode(value) do
    value
  end
end

