# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.AppComponentConfigConnection do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :component_id,
    :created_at,
    :created_by_id,
    :docker_build,
    :external_image,
    :helm,
    :id,
    :job,
    :terraform_module,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :component_id => String.t | nil,
    :created_at => String.t | nil,
    :created_by_id => String.t | nil,
    :docker_build => NuonAPI.Model.AppDockerBuildComponentConfig.t | nil,
    :external_image => NuonAPI.Model.AppExternalImageComponentConfig.t | nil,
    :helm => NuonAPI.Model.AppHelmComponentConfig.t | nil,
    :id => String.t | nil,
    :job => NuonAPI.Model.AppJobComponentConfig.t | nil,
    :terraform_module => NuonAPI.Model.AppTerraformModuleComponentConfig.t | nil,
    :updated_at => String.t | nil
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:docker_build, :struct, NuonAPI.Model.AppDockerBuildComponentConfig)
     |> Deserializer.deserialize(:external_image, :struct, NuonAPI.Model.AppExternalImageComponentConfig)
     |> Deserializer.deserialize(:helm, :struct, NuonAPI.Model.AppHelmComponentConfig)
     |> Deserializer.deserialize(:job, :struct, NuonAPI.Model.AppJobComponentConfig)
     |> Deserializer.deserialize(:terraform_module, :struct, NuonAPI.Model.AppTerraformModuleComponentConfig)
  end
end

