# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.Planv1Plan do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :actual
  ]

  @type t :: %__MODULE__{
    :actual => any() | nil
  }

  def decode(value) do
    value
  end
end

