# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServiceCreateHelmComponentConfigRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :chart_name,
    :connected_github_vcs_config,
    :public_git_vcs_config,
    :values
  ]

  @type t :: %__MODULE__{
    :chart_name => String.t,
    :connected_github_vcs_config => NuonAPI.Model.ServiceConnectedGithubVcsConfigRequest.t | nil,
    :public_git_vcs_config => NuonAPI.Model.ServicePublicGitVcsConfigRequest.t | nil,
    :values => %{optional(String.t) => String.t}
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:connected_github_vcs_config, :struct, NuonAPI.Model.ServiceConnectedGithubVcsConfigRequest)
     |> Deserializer.deserialize(:public_git_vcs_config, :struct, NuonAPI.Model.ServicePublicGitVcsConfigRequest)
  end
end

