# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServiceRepository do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :clone_url,
    :default_branch,
    :full_name,
    :git_url,
    :github_install_id,
    :name,
    :user_name
  ]

  @type t :: %__MODULE__{
    :clone_url => String.t,
    :default_branch => String.t,
    :full_name => String.t,
    :git_url => String.t,
    :github_install_id => String.t,
    :name => String.t,
    :user_name => String.t
  }

  def decode(value) do
    value
  end
end

