# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServiceCreateComponentReleaseRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :build_id,
    :strategy
  ]

  @type t :: %__MODULE__{
    :build_id => String.t | nil,
    :strategy => NuonAPI.Model.ServiceCreateComponentReleaseRequestStrategy.t | nil
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:strategy, :struct, NuonAPI.Model.ServiceCreateComponentReleaseRequestStrategy)
  end
end

