# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServiceCreateAppInputConfigRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :inputs
  ]

  @type t :: %__MODULE__{
    :inputs => %{optional(String.t) => NuonAPI.Model.ServiceAppInputRequest.t}
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:inputs, :map, NuonAPI.Model.ServiceAppInputRequest)
  end
end

