# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServiceCreateAppInstallerRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :links,
    :name,
    :slug
  ]

  @type t :: %__MODULE__{
    :description => String.t,
    :links => NuonAPI.Model.ServiceCreateAppInstallerRequestLinks.t | nil,
    :name => String.t,
    :slug => String.t
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:links, :struct, NuonAPI.Model.ServiceCreateAppInstallerRequestLinks)
  end
end

