# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServiceInstallerCreateInstallRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :aws_account,
    :name
  ]

  @type t :: %__MODULE__{
    :aws_account => NuonAPI.Model.ServiceCreateInstallRequestAwsAccount.t,
    :name => String.t
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:aws_account, :struct, NuonAPI.Model.ServiceCreateInstallRequestAwsAccount)
  end
end

