# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServiceCreateDockerBuildComponentConfigRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :build_args,
    :connected_github_vcs_config,
    :dockerfile,
    :env_vars,
    :public_git_vcs_config,
    :target
  ]

  @type t :: %__MODULE__{
    :build_args => [String.t] | nil,
    :connected_github_vcs_config => NuonAPI.Model.ServiceConnectedGithubVcsConfigRequest.t | nil,
    :dockerfile => String.t,
    :env_vars => %{optional(String.t) => String.t} | nil,
    :public_git_vcs_config => NuonAPI.Model.ServicePublicGitVcsConfigRequest.t | nil,
    :target => String.t | nil
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:connected_github_vcs_config, :struct, NuonAPI.Model.ServiceConnectedGithubVcsConfigRequest)
     |> Deserializer.deserialize(:public_git_vcs_config, :struct, NuonAPI.Model.ServicePublicGitVcsConfigRequest)
  end
end

