# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServiceCreateComponentReleaseRequestStrategy do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :delay,
    :installs_per_step
  ]

  @type t :: %__MODULE__{
    :delay => String.t | nil,
    :installs_per_step => integer() | nil
  }

  def decode(value) do
    value
  end
end

