# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServiceUpdateAppInstallerRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :links,
    :name
  ]

  @type t :: %__MODULE__{
    :description => String.t,
    :links => NuonAPI.Model.ServiceUpdateAppInstallerRequestLinks.t | nil,
    :name => String.t
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:links, :struct, NuonAPI.Model.ServiceUpdateAppInstallerRequestLinks)
  end
end

