# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServiceCreateOrgRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :use_custom_cert,
    :use_sandbox_mode
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :use_custom_cert => boolean() | nil,
    :use_sandbox_mode => boolean() | nil
  }

  def decode(value) do
    value
  end
end

