# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NuonAPI.Model.ServicePublishMetricInput do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :decr,
    :event,
    :incr,
    :timing
  ]

  @type t :: %__MODULE__{
    :decr => NuonAPI.Model.MetricsDecr.t | nil,
    :event => NuonAPI.Model.MetricsEvent.t | nil,
    :incr => NuonAPI.Model.MetricsIncr.t | nil,
    :timing => NuonAPI.Model.MetricsTiming.t | nil
  }

  alias NuonAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:decr, :struct, NuonAPI.Model.MetricsDecr)
     |> Deserializer.deserialize(:event, :struct, NuonAPI.Model.MetricsEvent)
     |> Deserializer.deserialize(:incr, :struct, NuonAPI.Model.MetricsIncr)
     |> Deserializer.deserialize(:timing, :struct, NuonAPI.Model.MetricsTiming)
  end
end

