---
name: Generate SDK
on:
  workflow_dispatch:
  repository_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  generate-sdk:
    name: Generate SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Enable commit signing
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.NUON_BOT_PRIVATE_KEY }}
          passphrase: ${{ secrets.NUON_BOT_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Generate SDK
        run: |
          ./scripts/generate.sh
      - name: Commit changes
        run: |
          git checkout -b nuonbot/api-version-$(cat version.txt)
          git add .
          git commit -m "chore: regenerate from api version $(cat version.txt)"
          git push -u origin nuonbot/api-version-$(cat version.txt)
      - name: Open PR
        run: |
          gh pr create --title "chore: regenerate from api version $(cat version.txt)" --body "chore: regenerate from api version $(cat version.txt)"
          gh pr merge --auto --delete-branch --squash nuonbot/api-version-$(cat version.txt)
