---
name: Generate SDK
on:
  workflow_dispatch:
  repository_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
  GET_VERSION: $(cat version.txt)
  BRANCH_NAME: "nuonbot/api-version-$GET_VERSION"
  COMMIT_MESSAGE: "chore: regenerate from api version $GET_VERSION"
jobs:
  generate-sdk:
    name: Generate SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Enable commit signing
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.NUON_BOT_PRIVATE_KEY }}
          passphrase: ${{ secrets.NUON_BOT_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Generate SDK
        run: |
          ./scripts/generate.sh
      - name: Commit changes
        run: |
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push -u origin $BRANCH_NAME
      - name: Open PR
        run: |
          gh pr create --title "$COMMIT_MESSAGE" --body "$COMMIT_MESSAGE"
          gh pr merge --auto --delete-branch --squash "$BRANCH_NAME"
