---
name: Generate SDK
on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version you want to publish. Must of format "1.0.0".
        required: true
env:
  BRANCH_NAME: "bot/update-for-api-${{ inputs.version }}"
  COMMIT_MESSAGE: "chore: update for api version ${{ inputs.version }}"
  GIT_USER_EMAIL: "<>"
  GIT_USER_NAME: "bot"
  GH_TOKEN: ${{ github.token }}
jobs:
  generate-sdk:
    name: Generate SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --global user.email $GIT_USER_EMAIL
          git config --global user.name $GIT_USER_NAME
      - name: Create branch
        run: |
          git checkout -b $BRANCH_NAME
      - name: Generate SDK
        run: |
          ./scripts/generate.sh
      - name: Commit changes
        run: |
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push -u origin $BRANCH_NAME
      - name: Open PR
        run: |
          gh pr create --title "$COMMIT_MESSAGE" --body "$COMMIT_MESSAGE"
          gh pr merge --auto --delete-branch --squash "$BRANCH_NAME"
