---
name: Generate
on:
  workflow_dispatch:
  repository_dispatch:
    types: [generate]
jobs:
  generate:
    uses: nuonco/.github/.github/workflows/generate.yml@ja/3498-shared-sdk-workflows
    secrets: inherit
