---
name: Pull Request
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check-pr:
    uses: nuonco/.github/.github/workflows/pull_request.yml@ja/3498-shared-sdk-workflows
    secrets: inherit
