---
name: release
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  release:
    name: Tag new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Release
        id: release
        run: gh release create $(cat version.txt) --generate-notes --target main
