---
name: Release
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  GH_TOKEN: ${{ github.token }}
  HEX_API_KEY: ${{ secrets.HEX_GITHUB_TOKEN }}
jobs:
  release:
    uses: nuonco/.github/.github/workflows/release.yml@ja/3498-shared-sdk-workflows
    secrets: inherit
